### ISSUE TITLE
More algorithms

### ISSUE THREAD

**Issue by fabianonline** [glueckkanja-pki/PKI-Configuration-Tools#1]
This script currently only sets SHA256 as usable algorithms, preventing users from doing encryption.

In order to be able to use encryption as well, you can replace `$binAlgorithms` in 
https://github.com/glueckkanja-pki/PKI-Configuration-Tools/blob/92dec943f523836512728e4c5b72fe6d3fad5f00/ActivateSignatures.ps1#L211

by this:
` [byte[]] $binAlgorithms = 0x02, 0x00, 0x89, 0x00, 0x30, 0x81, 0x82, 0x30, 0x0b, 0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x01, 0x2a, 0x30, 0x0b, 0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x01, 0x16, 0x30, 0x0a, 0x06, 0x08, 0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x03, 0x07, 0x30, 0x0b, 0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x01, 0x02, 0x30, 0x0e, 0x06, 0x08, 0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x03, 0x02, 0x02, 0x02, 0x00, 0x80, 0x30, 0x0d, 0x06, 0x08, 0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x03, 0x02, 0x02, 0x01, 0x40, 0x30, 0x0b, 0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x02, 0x01, 0x30, 0x0b, 0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x02, 0x03, 0x30, 0x0b, 0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x02, 0x02, 0x30, 0x07, 0x06, 0x05, 0x2b, 0x0e, 0x03, 0x02, 0x1a`

This allows the use of AES-256 and other encryption algorithms.

**Comment by bb-froggy** [comment]
Well observed, thank you!

I updated the script, but I removed the outdated RC2 from the set of allowed algorithms. And since I were at it, I also removed SHA-1, as SHA-2 should be compatible with everything.
